# Generated by Django 3.1.3 on 2020-11-24 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BattleEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(db_index=True)),
                ('system', models.CharField(max_length=1024)),
                ('alliance', models.CharField(max_length=1024)),
                ('type', models.CharField(choices=[('capture', 'Capture'), ('defence', 'Defence')], max_length=255)),
            ],
        ),
    ]
