# Generated by Django 3.1.3 on 2020-11-24 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battle_schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battleevent',
            old_name='system',
            new_name='territory',
        ),
    ]
