# Generated by Django 3.1.3 on 2020-11-24 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battle_schedule', '0002_auto_20201124_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('takeover_day', models.CharField(choices=[(1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday'), (7, 'Saturday')], max_length=255)),
                ('takeover_time', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='battleevent',
            name='territory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle_schedule.territory'),
        ),
    ]
