# Generated by Django 3.1.3 on 2020-11-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle_schedule', '0003_auto_20201124_1233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='territory',
            options={'ordering': ('name',), 'verbose_name_plural': 'Territories'},
        ),
        migrations.AlterField(
            model_name='territory',
            name='takeover_day',
            field=models.IntegerField(choices=[(1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday'), (7, 'Saturday')], max_length=255),
        ),
    ]
