# Generated by Django 3.1.3 on 2020-11-24 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battle_schedule', '0004_auto_20201124_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battleevent',
            name='time',
        ),
    ]
