# Generated by Django 3.1.3 on 2020-11-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle_schedule', '0005_remove_battleevent_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='territory',
            name='takeover_day',
            field=models.IntegerField(choices=[(1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday'), (7, 'Saturday')]),
        ),
    ]
