# Generated by Django 3.1.3 on 2020-11-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle_schedule', '0007_battleevent_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battleevent',
            name='alliance',
            field=models.CharField(default='No alliance set.', max_length=1024),
        ),
        migrations.AlterField(
            model_name='battleevent',
            name='type',
            field=models.CharField(choices=[('capture', 'Capture'), ('defence', 'Defence')], default='defence', max_length=255),
        ),
    ]
