# Generated by Django 3.1.3 on 2020-11-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle_schedule', '0008_auto_20201124_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battleevent',
            name='type',
            field=models.CharField(choices=[('neutral', 'Neutral'), ('capture', 'Capture'), ('defence', 'Defence')], default='neutral', max_length=255),
        ),
    ]
