# Generated by Django 3.1.3 on 2020-12-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle_schedule', '0010_auto_20201125_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleScheduleNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=1024)),
                ('last_time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
