# Generated by Django 3.1.3 on 2020-12-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle_schedule', '0011_battleschedulenotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battleschedulenotification',
            name='last_time',
        ),
        migrations.AddField(
            model_name='battleschedulenotification',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
