# Generated by Django 3.1.3 on 2020-12-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle_schedule', '0012_auto_20201213_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='battleschedulenotification',
            name='initialized',
            field=models.BooleanField(default=False),
        ),
    ]
