# Generated by Django 3.1.3 on 2020-12-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle_schedule', '0013_battleschedulenotification_initialized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battleschedulenotification',
            name='last_update',
            field=models.DateTimeField(),
        ),
    ]
