# Generated by Django 3.1.3 on 2020-12-14 16:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('battle_schedule', '0014_auto_20201214_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battleschedulenotification',
            name='last_update',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
